import type { Meta, StoryObj } from '@storybook/react';
import { Paragraph } from './Paragraph';
import { AIProvider } from '../../providers/AIProvider';
import type { AIClient } from '../../contexts/AIContext';

const meta: Meta<typeof Paragraph> = {
  title: 'Typography/Paragraph',
  component: Paragraph,
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof Paragraph>;

export const Default: Story = {
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <Paragraph>
        This library is styled entirely through --ds-* CSS variables, so components never change
        when the underlying design tokens do.
      </Paragraph>
      <Paragraph>Consecutive paragraphs get spacing between them automatically.</Paragraph>
    </div>
  ),
};

const mockAIClient: AIClient = {
  complete: async () =>
    'The library uses CSS variables for styling so it can adopt real design tokens later without touching component code.',
};

/**
 * `aiSummarize` is a no-op without an ancestor `AIProvider` — this story
 * wraps a deterministic mock client so the "Summarize with AI" trigger
 * actually appears. Read-only, same shape as `Alert`'s `aiExplain`: no
 * accept/reject, just a summary.
 */
export const WithAISummarize: Story = {
  decorators: [
    (Story) => (
      <AIProvider client={mockAIClient}>
        <Story />
      </AIProvider>
    ),
  ],
  render: () => (
    <div style={{ maxWidth: 480 }}>
      <Paragraph aiSummarize>
        This library is styled entirely through --ds-* CSS variables, so components never change
        when the underlying design tokens do. The token package is generated by a separate Design
        System Foundation repository and published on npm as @mellon-design/tokens-web.
      </Paragraph>
    </div>
  ),
};
